### ISSUE TITLE
Is this correct ?

### ISSUE THREAD

**Issue by sgrayban** [cl0udninja/raspberrypi.monitor#2] opened 2018-10-16 18:25 UTC
The only close to raspberrypi.monitor.jar is below thta I saw when it installed. Is this correct ? If so I can't seem to get upnp support going.

/root/.m2/repository/com/cl0udninja/raspberrypi.monitor/0.0.1-SNAPSHOT/raspberrypi.monitor-0.0.1-SNAPSHOT.jar

**Comment by cl0udninja** [comment] 2018-10-16 19:49
Hi,

The UPnP is kind of dodgy and in a couple of days it actually make the java service to terminate. I didn't spend time on it to find the root cause, so I have another version of this w/o the UPNP support: https://github.com/cl0udninja/janipi Although it has additional services as well.

The UPnP however is configured in `src/main/resources/application.properties` It defaults to the below values:

``` java
# UPnP
upnp.response.port=50000
upnp.config.address=192.168.1.40
emulator.portbase=8080
emulator.portcount=1
upnp.disable=false
```
I would suggest to look at whether the IP address is correct and whether the port specified above is available through your firewall on the PI if there's any.

If you make changes to the above file you'll have to run `mvn clean install` again!

If you wish to drop UPnP for a more stable version of this simply follow the instructions here: https://community.smartthings.com/t/raspberry-pi-monitor/115372/39?u=cl0udninja

I hope this helps!

**Comment by sgrayban** [comment] 2018-10-16 20:27
Does https://github.com/cl0udninja/janipi also work with your smart app ?

**Comment by cl0udninja** [comment] 2018-10-16 20:29
It should. It uses the DH w/ the manual IP. It doesn't support UPnP

**Comment by sgrayban** [comment] 2018-10-16 20:29
ok

**Comment by sgrayban** [comment] 2018-10-16 20:46
does jani also run on port 8080 ?

**Comment by cl0udninja** [comment] 2018-10-16 20:49
Yes it does

On Oct 16, 2018 1:47 PM, "Scott Grayban" <notifications@github.com> wrote:

does jani also run on port 8080 ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cl0udninja/raspberrypi.monitor/issues/2#issuecomment-430394411>,
or mute the thread

**Comment by sgrayban** [comment] 2018-10-16 20:50
doesnt pick up the new PI 3B+ says unknown

**Comment by sgrayban** [comment] 2018-10-16 20:53
also seems there is a error in the api page...

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Oct 16 13:51:21 PDT 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by cl0udninja** [comment] 2018-10-16 20:56
do you run it with `sudo`? Pi4J needs root access for some reason.

**Comment by sgrayban** [comment] 2018-10-16 21:17
yes and same error still -- even recompiled it

**Comment by cl0udninja** [comment] 2018-10-16 21:20
Then I'll need you to send the the exception from the log file. Also note that `/api` doesn't support browsing you need to type in the full address: `/api/pi`

The logfile should be in `/var/log`

**Comment by sgrayban** [comment] 2018-10-16 21:22
nothing is logging to that file

**Comment by cl0udninja** [comment] 2018-10-16 21:25
it is a directory

**Comment by sgrayban** [comment] 2018-10-16 21:27
i know that... nothing is in the log file... I'm not a noob to linux as I have developed countless of linux programs

# ll /var/log/raspberrypi.monitor.log 
-rw-rw-rw- 1 root root 0 Oct 16 12:32 /var/log/raspberrypi.monitor.log

**Comment by sgrayban** [comment] 2018-10-16 21:27
I even chmod 666 and nothing logged

**Comment by sgrayban** [comment] 2018-10-16 21:28
only thing logging is the startup in

[root@office janipi]
# ll raspberrypi.monitor.log
-rw-r--r-- 1 root root 89525 Oct 16 14:23 raspberrypi.monitor.log

**Comment by cl0udninja** [comment] 2018-10-16 21:30
ok are you run it from the command line? like 

```
sudo java -jar my.jar
```
?
If yes it prints the log to the console. While it is running and printed out that the application is finished starting (it will log it to the console) then enter in your browser: `http:/myraspberrypi:8080/api/pi` and then tell me what is the exception on the console

Feel free to paste in the whole thing from the get go! :)

**Comment by sgrayban** [comment] 2018-10-16 21:31
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Oct 16 14:24:16 PDT 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by cl0udninja** [comment] 2018-10-16 21:32
there's no way that's on your bash console

**Comment by cl0udninja** [comment] 2018-10-16 21:32
That's on your browser window!

**Comment by sgrayban** [comment] 2018-10-16 21:33
I told you there is NO ERROR OUT PUT IN ANYTHING

**Comment by sgrayban** [comment] 2018-10-16 21:35
last few lines after I go to the url are:

2018-10-16 14:34:27.534  INFO 25930 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-10-16 14:34:27.556  INFO 25930 --- [           main] c.c.raspberrypi.monitor.Application      : Started Application in 18.383 seconds (JVM running for 20.48)
2018-10-16 14:34:41.299  INFO 25930 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-10-16 14:34:41.300  INFO 25930 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-10-16 14:34:41.448  INFO 25930 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 147 ms

**Comment by cl0udninja** [comment] 2018-10-16 21:35
what is the url in the browser?

**Comment by sgrayban** [comment] 2018-10-16 21:36
http://office:8080/api/api

**Comment by cl0udninja** [comment] 2018-10-16 21:36
please try http://office:8080/api/pi

**Comment by sgrayban** [comment] 2018-10-16 21:37
mf..........

**Comment by cl0udninja** [comment] 2018-10-16 21:37
`api/api` is not a url the application has a listener on. that explains the lack of log entries and the http 404

**Comment by cl0udninja** [comment] 2018-10-16 21:37
did it work now? :)

**Comment by sgrayban** [comment] 2018-10-16 21:38
i would have left it as api just to be compatiable

yes its working

**Comment by cl0udninja** [comment] 2018-10-16 21:39
well `/api` is a prefix, and then comes the different endpoints. like `api/temperature` or `api/flower` and so on :) 

Allow me to close this issue then :)

**Comment by sgrayban** [comment] 2018-10-16 21:39
one thing

**Closed as completed by cl0udninja** 2018-10-16 21:39 UTC

**Comment by sgrayban** [comment] 2018-10-16 21:40
What I liked was the temp being shown from the other monitor instead of the load value

**Comment by sgrayban** [comment] 2018-10-16 21:40
or im assuming its the load

**Comment by cl0udninja** [comment] 2018-10-16 21:43
You can change that in the DH. I changed that to the free mem instead. Just open the DH in SmartThings IDE replace the line 

```
main "freeMemoryPercent"
```
with
```
main "cpuTemperature"
```

Then click save and publish. Refresh the list in your mobile app and it should show the temperature

**Comment by sgrayban** [comment] 2018-10-16 21:43
ya i just did that

thanks for your help !!

**Comment by cl0udninja** [comment] 2018-10-16 21:44
np :)
